console.log('Feature 1')
console.log('Feature 2')
console.log('Feature 3')
console.log('Feature 4 [bug]')
console.log('Feature 5')
console.log('Feature 6')
console.log('Feature 1 of b1')
console.log('Feature 2 of b1')
console.log('Feature 1 of b2')